DM-34964: add cancel, restart and ping function in the bps panda plugin
lsst/ctrl_bps_panda pull request #11
Opened 2022-06-06 18:15 UTC by wguanicedew

## Checklist

- [x] ran Jenkins
- [x] added a release note for user-visible changes to `doc/changes`

2022-06-07 15:58 UTC, timj requested changes
I am assuming @MichelleGower will also take a look from a bps perspective.

I have many comments but I think most of them are easy to deal with.

I do have a concern about the return values from idds APIs being very hard to use. It looks like there are tuples with tuples and the code here would benefit significantly from those APIs returning objects that can be inspected with methods.

Code like this:

```
if ret[0] == 0 and ret[1][0]
```
is very hard to follow and would be much easier if `ret` was an object that could have methods run on it.

2022-06-07 15:58 UTC, timj commented on python/lsst/ctrl/bps/panda/panda_service.py
> +            raise RuntimeError(f"Error to get workflow status: {str(ret)}")
Again, `str` not needed.

2022-06-07 15:58 UTC, timj commented on python/lsst/ctrl/bps/panda/panda_service.py
> +        ret = c.get_requests(request_id=wms_id)
Better variable name needed.

2022-06-07 15:58 UTC, timj commented on python/lsst/ctrl/bps/panda/panda_service.py
> +        if ret[0] == 0 and ret[1][0]:
This logic is used a lot and it is starting to worry me that `ret` should be a class on which you can ask questions like this.

2022-06-07 15:58 UTC, timj commented on python/lsst/ctrl/bps/panda/panda_service.py
> +                success = True
Setting `success` to `True` every time round the loop seems excessive. I think you are saying that `success` should be `True` if `reqs` has any content? How about:

```python
req_ids = []
if ret[0] == 0 and ret[1][0]:
    req_ids = [req["request_id"] for req in ret[1][1]]

if not req_ids:
    raise RuntimeError(...)

return req_ids
```

2022-06-07 15:58 UTC, timj commented on python/lsst/ctrl/bps/panda/panda_service.py
> +        _LOG.debug("Abort PanDA workflow returned = %s", str(ret))
No `str` needed

2022-06-07 15:58 UTC, timj commented on python/lsst/ctrl/bps/panda/panda_service.py
> +        ret = c.abort(request_id=wms_id)
variable name.

2022-06-07 15:58 UTC, timj commented on python/lsst/ctrl/bps/panda/panda_service.py
> +                if type(req) in [tuple, list]:
Restrictive type check. At least comment that you are deliberately constraining to tuple/list and no duck-typing a Sequence.

2022-06-07 15:58 UTC, timj commented on python/lsst/ctrl/bps/panda/panda_service.py
> +        success = True
How does `success` ever get set to `False`?

2022-06-10 15:18 UTC, wguanicedew commented on doc/changes/DM-34964.rst
> +Add cancel,restart, report and ping functions in bps panda plugin.
fixed.

2022-06-10 15:23 UTC, wguanicedew commented on python/lsst/ctrl/bps/panda/panda_service.py
> +        idds_client: `iDDS client manager object`
fixed.

2022-06-10 15:25 UTC, wguanicedew commented on python/lsst/ctrl/bps/panda/panda_service.py
> +        if type(self.config) in [BpsConfig]:
updated.

2022-06-10 15:29 UTC, wguanicedew commented on python/lsst/ctrl/bps/panda/panda_service.py
> +        ret = c.abort(request_id=wms_id)
updated.

2022-06-10 15:37 UTC, wguanicedew commented on python/lsst/ctrl/bps/panda/panda_service.py
> +        elif type(self.config) in [dict] and "iddsServer" in self.config:
I updated to use isinstance.
For bps submit, a bps yaml file is read. So it returns BpsConfig and a config.search function can be called.
But in bps abort, for example, no yaml file is read. Here the config part is a dict. It doesn't have search function.

2022-06-10 15:51 UTC, wguanicedew commented on python/lsst/ctrl/bps/panda/panda_service.py
> +        Parameters
updated.

2022-06-10 15:55 UTC, wguanicedew commented on python/lsst/ctrl/bps/panda/panda_service.py
> +            raise RuntimeError(f"Error to retry workflow: {str(ret)}")
updated.

2022-06-10 16:05 UTC, wguanicedew commented on python/lsst/ctrl/bps/panda/panda_service.py
> +        if ret[0] == 0 and ret[1][0]:
new functions to replace it.

2022-06-10 16:08 UTC, wguanicedew commented on python/lsst/ctrl/bps/panda/panda_service.py
> +                for state in WmsStates:
It's required in bps. Without setting this part, bps report will raise errors.

2022-06-10 16:09 UTC, wguanicedew commented on python/lsst/ctrl/bps/panda/panda_service.py
> +                success = True
fixed.

2022-06-10 16:19 UTC, timj commented on python/lsst/ctrl/bps/panda/panda_service.py
> +                for state in WmsStates:
I'm confused. I was suggesting a more compact way of filling the `job_state_counts` variable. Not saying to remove the code. It looked like the three lines could be replaced by the one I suggested.

2022-06-10 16:19 UTC, wguanicedew commented on python/lsst/ctrl/bps/panda/panda_service.py
> +        ret = c.get_requests(request_id=wms_workflow_id, with_detail=True)
updated.

2022-06-10 16:23 UTC, wguanicedew commented on python/lsst/ctrl/bps/panda/panda_service.py
> +        ret = c.retry(request_id=wms_workflow_id)
yes. However I reformat this function.

2022-06-10 16:25 UTC, wguanicedew commented on python/lsst/ctrl/bps/panda/panda_service.py
> +        _LOG.debug("Retry PanDA workflow returned = %s", str(ret))
The ret is a tuple. without str, only ret[0] will match the '%s'. Then it will raise errors such as not all items are formatted.

2022-06-10 16:25 UTC, wguanicedew commented on python/lsst/ctrl/bps/panda/panda_service.py
> +                if type(req) in [tuple, list]:
reformatted this function.

2022-06-10 16:27 UTC, timj commented on python/lsst/ctrl/bps/panda/panda_service.py
> +        _LOG.debug("Retry PanDA workflow returned = %s", str(ret))
I don't think so:

```
>>> x = (1, 3, 4)
>>> logging.warning("Tuple: %s", x)
WARNING:root:Tuple: (1, 3, 4)
```
That seems to stringify the tuple (you aren't doing `*ret`).

2022-06-10 22:14 UTC, wguanicedew commented on python/lsst/ctrl/bps/panda/panda_service.py
> +        _LOG.debug("Retry PanDA workflow returned = %s", str(ret))
ok. updated. Thanks.

2022-06-10 22:15 UTC, wguanicedew commented on python/lsst/ctrl/bps/panda/panda_service.py
> +                for state in WmsStates:
Sorry. I missed understood. Thanks.

2022-06-13 16:09 UTC, timj commented on python/lsst/ctrl/bps/panda/panda_service.py
> +            ret: `(int, (bool, payload))`
The indent is wrong her and below.

2022-06-13 16:10 UTC, timj commented on python/lsst/ctrl/bps/panda/panda_service.py
> +        idds_client: `ClientManager`
Does this render okay if you do `package-docs build`? I think it might need the full name of the iDDS class.

2022-06-14 15:47 UTC, timj commented on python/lsst/ctrl/bps/panda/panda_service.py
> +        idds_client: `ClientManager`
@wguanicedew change the target python version in pyproject.toml. We forgot to change it to py310 when we migrated to py310.

2022-06-14 21:51 UTC, MichelleGower reviewed
In my tests, report isn't working as expected.   Also, the behavior in error cases isn't the same as the expected behavior for all of the new functions.  And a heads up that the expected ping method signature will be different than it appears here.

2022-06-14 21:51 UTC, MichelleGower commented on python/lsst/ctrl/bps/panda/panda_service.py
> +            return run_reports, message
When I run this with `--id 1512` I get 21 runs.  I expected 1 run with 120+ jobs across 21 job labels.

2022-06-15 17:54 UTC, wguanicedew commented on python/lsst/ctrl/bps/panda/panda_service.py
> +            raise RuntimeError(f"Error retry PanDA workflow: {error}")
Working to reformat the functions to replace RuntimeError to messages. Will test them again.

2022-06-15 17:58 UTC, wguanicedew commented on python/lsst/ctrl/bps/panda/panda_service.py
> +            return run_reports, message
Here I put one run per panda task. What do you mean job labels? How to map 21 panda tasks to different job labels?

2022-06-15 18:06 UTC, MichelleGower commented on python/lsst/ctrl/bps/panda/panda_service.py
> +            return run_reports, message
a bps "run" is a single butler output collection which is a single workflow being submitted to WMS.   As for how to map PanDA tasks to job labels, I'm not sure how to do this in PanDA.  Each GenericWorkflowJob has a label.  I don't know if that's lost once submitted to PanDA or not.

2022-06-15 19:04 UTC, wguanicedew commented on python/lsst/ctrl/bps/panda/panda_service.py
> +            return run_reports, message
ok. I will check at first whether the label is kept or not. Then we can discuss how to map the jobs to different labels.

2022-06-19 21:04 UTC, wguanicedew commented on python/lsst/ctrl/bps/panda/panda_service.py
> +            ret: `(int, (bool, payload))`
updated and tested with "package-docs build"

2022-06-19 21:04 UTC, wguanicedew commented on python/lsst/ctrl/bps/panda/panda_service.py
> +        wms_state: `WmsStates`
updated.

2022-06-19 21:14 UTC, wguanicedew commented on python/lsst/ctrl/bps/panda/panda_service.py
> +
updated to add lines to report errors.

2022-06-19 21:24 UTC, wguanicedew commented on python/lsst/ctrl/bps/panda/panda_service.py
> +        idds_client: `ClientManager`
updated and tested ok with packages-docs build.

2022-06-24 11:49 UTC, wguanicedew commented on python/lsst/ctrl/bps/panda/panda_service.py
> +    def ping(self):
updated.

2022-06-24 11:50 UTC, wguanicedew commented on python/lsst/ctrl/bps/panda/panda_service.py
> +            return run_reports, message
report function is removed from this ticket.

2022-06-28 17:50 UTC, MichelleGower commented on python/lsst/ctrl/bps/panda/panda_service.py
> +            msg += " and filtering worflows with 'user' is not supported."
Thanks for adding the check and nicer error message.

Typo (missing k):  filtering worflows -> filtering workflows

2022-06-28 19:37 UTC, wguanicedew commented on python/lsst/ctrl/bps/panda/panda_service.py
> +            msg += " and filtering worflows with 'user' is not supported."
fixed.

2022-06-28 19:41 UTC, timj commented on python/lsst/ctrl/bps/panda/panda_service.py
> +            raise RuntimeError(msg)
Can you do it instead as:
```python
raise RuntimeError("Error to get workflow status report: wms_id is required"
    " and filtering workflows with 'user' is not supported.")
```
there is no real need to do the separate variable and concatenation. I think the `msg` line could be done without the `+=`:

```python
msg = ("Error to get workflow status report: wms_id is required"
       " and filtering workflows with 'user' is not supported.")
```
(and black would likely fix it up for you if you just made the line long)

2022-06-28 20:28 UTC, wguanicedew commented on python/lsst/ctrl/bps/panda/panda_service.py
> +            raise RuntimeError(msg)
It's good. Thanks. I updated it.

2022-07-07 12:32 UTC, merged