DM-37298 Add usage message for bps report in PanDA plugin
lsst/ctrl_bps_panda pull request #32
Opened 2022-12-14 20:38 UTC by zhaoyuyoung

## Checklist

- [ ] ran Jenkins
- [ ] added a release note for user-visible changes to `doc/changes`

2022-12-15 10:33 UTC, wguanicedew requested changes
I am not sure whether sys.exit is a good idea. If 'raise RuntimeError' can work, I would prefer you switch to use it. Because if someone use it as an API, 'sys.exit' will cause the caller fails.

2022-12-15 17:22 UTC, mxk62 commented on python/lsst/ctrl/bps/panda/panda_service.py
>              raise RuntimeError(f"Error to get workflow status: {ret} for id: {wms_workflow_id}")
Just FYI, I realized that this exception will not be handled by the method's caller, the `report()` function. As a result, the user will see entire traceback that lead to this error. And that may be perfectly fine in this case as I'm assuming the issues with iDDS sever are important enough that it is better to provide entire traceback instead of the brief error message. However, if this is *not* a critical error you still may want just to pass the error message like any other.

2022-12-15 18:03 UTC, zhaoyuyoung commented on python/lsst/ctrl/bps/panda/panda_service.py
> +            sys.exit(1)
I'll change accordingly.

2022-12-15 18:03 UTC, zhaoyuyoung commented on python/lsst/ctrl/bps/panda/panda_service.py
> +            sys.exit(1)
same here, will be changed.

2022-12-15 18:15 UTC, zhaoyuyoung commented on python/lsst/ctrl/bps/panda/panda_service.py
>              raise RuntimeError(f"Error to get workflow status: {ret} for id: {wms_workflow_id}")
True. For this exception, I leave it as is.

2022-12-15 18:16 UTC, zhaoyuyoung commented on python/lsst/ctrl/bps/panda/panda_service.py
> +        if not tasks:
Moved. I know it's better for reading.

2022-12-16 19:51 UTC, wguanicedew approved these changes
Looks good for me.

2022-12-16 21:09 UTC, merged